#!/usr/bin/env bash
#
# this program has only been tested with parity ethereum client!
set -x
tx=`seth rpc signer_requestsToConfirm | tail -n1 | jshon -e payload -e sendTransaction`
from=`echo $tx|jshon -e from -u`
nonce=$(seth --to-hex `seth nonce $from`)
tx=`echo $tx|jshon -s $nonce -i nonce`
for i in gas gasPrice nonce value; do
	dec=$(seth --to-dec $(echo $tx|jshon -e $i -u))
	tx=$(echo $tx|jshon -n $dec -i $i)
done
qr "$tx"
echo $tx
