#!/usr/bin/env bash
#
echo "Hit CTRL-c to stop reading QR code sequence!"
trap "break" SIGINT
new=''
pcount=1
while : 
do
	raw="`zbarcam --raw --nodisplay| tee >(ifne killall zbarcam)`"
	tx="`echo $raw|sed -e 's/^\([0-9]\+\)-\(.*\)/\2/'`"
	count="`echo $raw|sed -e 's/^\([0-9]\+\)-\(.*\)/\1/'`"
	echo "$count. QR code received."
	if [[ $count -eq $pcount ]]; then
		new="$new$tx"
		pcount="$(( $pcount + 1 ))"
	else
		echo "You sent $count. QR code, but we expect the $pcount. QR code! Repeat pls!"
	fi
	sleep 1

done
printf "Raw TX: '$new'\nMining of tx in progress...\n"
txhash=`seth publish $new` && printf "Tx published! Hash: $txhash\n"
