#!/usr/bin/env bash
#
set -x
tx=`termux-clipboard-get`
echo $tx
txkeys=`echo $tx|jshon -k|sed -e "s/\\[/(/g"|sed -e "s/\\]/)/g"|sed -e "s/\"//g"|sed -e "s/,/ /g"`
signjson=''
for row in $txkeys ; do 
	[[ $row == "condition" ]] && [[ `echo $tx | jshon -e "condition" -u` -eq "null"  ]] && continue
	signjson=$signjson" --$row `echo $tx | jshon -e $row -u`"
done	
signjson="ethsign $signjson"
raw=$($signjson)
raw=`echo $raw| cut -d " " -f 2`
qr $raw
