#!/data/data/com.termux/files/usr/bin/env bash
set -e
export HOME=/data/data/com.termux/files/home
export GOBIN=$HOME/dapptools/src/ethsign
cd $HOME 
pkg install golang git termux-api nodejs tar clang vim python yarn 
pip install qrcode  
git clone https://github.com/dapphub/dapptools.git
cd dapptools 
git checkout 72037d4e32fc5bf9e66a03ba70689a839139a7b8  
cd $HOME 
git clone https://github.com/ethereum/go-ethereum.git 
mkdir -p go/src/github.com/ethereum/ 
mv go-ethereum go/src/github.com/ethereum 
cd go/src/github.com/ethereum/go-ethereum
git checkout v1.8.1 
cd $HOME 
git clone https://github.com/urfave/cli 
mkdir -p go/src/gopkg.in/urfave/ 
mv cli go/src/gopkg.in/urfave/ 
cd go/src/gopkg.in/urfave/ 
mv cli cli.v1 
cd cli.v1 
git checkout v1.19.1 
cd $HOME 
git clone https://go.googlesource.com/crypto 
mkdir -p go/src/golang.org/x/ 
mv crypto go/src/golang.org/x/ 
cd go/src/golang.org/x/crypto 
git checkout 94eea52f7b742c7cbe0b03b22f0c4c8631ece122 
cd $HOME 
git clone https://go.googlesource.com/sys 
mkdir -p go/src/golang.org/x/ 
mv sys go/src/golang.org/x/ 
cd go/src/golang.org/x/sys 
git checkout 53aa286056ef226755cd898109dbcdaba8ac0b81 
cd $HOME 
cd dapptools/src/ethsign 
go install ethsign.go 
cp ethsign $HOME/../usr/bin
cd $HOME/airsign
yarn install
