#!/data/data/com.termux/files/usr/bin/env bash
set -e -x
export HOME=/data/data/com.termux/files/home
cd $HOME 
pkg install git termux-api nodejs tar vim python yarn sed -y
pip install qrcode  
cd $HOME/airsign
yarn install
